version: '3.8'

services:

  db:
    container_name: users-table-mysql
    image: mysql
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    expose:
      - '${DATABASE_PORT}'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend

  node:
    container_name: users-table-node
    depends_on:
      - db
    build: ./server
    restart: unless-stopped
    env_file: .env
    ports:
      - $PORT:$PORT
    expose:
      - $PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
      - JWT_KEY=$JWT_KEY
      - HOST=$HOST
      - PORT=$PORT
    networks:
      - backend
      - frontend

  react:
    depends_on:
      - node
    build:
      context: ./client
    ports:
      - 3000:80
    networks:
      - frontend

volumes:
  my-db:


networks:
  backend:
  frontend:
